name: SCC
run-name: SCC

on:
  push:
    branches:
      - '*'
jobs:
  Test:
    name: JDK ${{ matrix.jdk }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: [ 11, 17 ]
        os: [ windows-latest ]
      fail-fast: true
      max-parallel: 4
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Set up Java ${{ matrix.jdk }}
        if: ${{ matrix.jdk != '8' }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Install
        # download dependencies, etc, so test log looks better
        run: mvn -B install